-- Data export for table languages

INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('1', 'ab', 'Abkhazian', 'аҧсуа', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('2', 'aa', 'Afar', 'Afaraf', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('3', 'af', 'Afrikaans', 'Afrikaans', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('4', 'ak', 'Akan', 'Akan', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('5', 'sq', 'Albanian', 'Shqip', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('6', 'am', 'Amharic', 'አማርኛ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('7', 'ar', 'Arabic', 'العربية', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('8', 'an', 'Aragonese', 'Aragonés', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('9', 'hy', 'Armenian', 'Հայերեն', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('10', 'as', 'Assamese', 'অসমীয়া', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('11', 'av', 'Avaric', 'авар мацӀ, магӀарул мацӀ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('12', 'ae', 'Avestan', 'avesta', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('13', 'ay', 'Aymara', 'aymar aru', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('14', 'az', 'Azerbaijani', 'azərbaycan dili', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('15', 'bm', 'Bambara', 'bamanankan', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('16', 'ba', 'Bashkir', 'башҡорт теле', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('17', 'eu', 'Basque', 'euskara, euskera', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('18', 'be', 'Belarusian', 'Беларуская', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('19', 'bn', 'Bengali', 'বাংলা', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('20', 'bh', 'Bihari', 'भोजपुरी', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('21', 'bi', 'Bislama', 'Bislama', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('22', 'bs', 'Bosnian', 'bosanski jezik', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('23', 'br', 'Breton', 'brezhoneg', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('24', 'bg', 'Bulgarian', 'български език', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('25', 'my', 'Burmese', 'ဗမာစာ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('26', 'ca', 'Catalan; Valencian', 'Català', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('27', 'ch', 'Chamorro', 'Chamoru', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('28', 'ce', 'Chechen', 'нохчийн мотт', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('29', 'ny', 'Chichewa; Chewa; Nyanja', 'chiCheŵa, chinyanja', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('30', 'zh', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('31', 'cv', 'Chuvash', 'чӑваш чӗлхи', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('32', 'kw', 'Cornish', 'Kernewek', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('33', 'co', 'Corsican', 'corsu, lingua corsa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('34', 'cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('35', 'hr', 'Croatian', 'hrvatski', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('36', 'cs', 'Czech', 'česky, čeština', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('37', 'da', 'Danish', 'dansk', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('38', 'dv', 'Divehi; Dhivehi; Maldivian;', 'ދިވެހި', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('39', 'nl', 'Dutch', 'Nederlands, Vlaams', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('40', 'en', 'English', 'English', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('41', 'eo', 'Esperanto', 'Esperanto', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('42', 'et', 'Estonian', 'eesti, eesti keel', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('43', 'ee', 'Ewe', 'Eʋegbe', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('44', 'fo', 'Faroese', 'føroyskt', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('45', 'fj', 'Fijian', 'vosa Vakaviti', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('46', 'fi', 'Finnish', 'suomi, suomen kieli', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('47', 'fr', 'French', 'français', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('48', 'ff', 'Fula; Fulah; Pulaar; Pular', 'Fulfulde, Pulaar, Pular', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('49', 'gl', 'Galician', 'Galego', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('50', 'ka', 'Georgian', 'ქართული', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('51', 'de', 'German', 'Deutsch', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('52', 'el', 'Greek, Modern', 'Ελληνικά', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('53', 'gn', 'Guaraní', 'Avañeẽ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('54', 'gu', 'Gujarati', 'ગુજરાતી', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('55', 'ht', 'Haitian; Haitian Creole', 'Kreyòl ayisyen', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('56', 'ha', 'Hausa', 'Hausa, هَوُسَ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('57', 'he', 'Hebrew', 'עברית', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('58', 'iw', 'Hebrew', 'עברית', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('59', 'hz', 'Herero', 'Otjiherero', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('60', 'hi', 'Hindi', 'हिन्दी, हिंदी', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('61', 'ho', 'Hiri Motu', 'Hiri Motu', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('62', 'hu', 'Hungarian', 'Magyar', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('63', 'ia', 'Interlingua', 'Interlingua', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('64', 'id', 'Indonesian', 'Bahasa Indonesia', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('65', 'ie', 'Interlingue', 'Originally called Occidental; then Interlingue after WWII', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('66', 'ga', 'Irish', 'Gaeilge', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('67', 'ig', 'Igbo', 'Asụsụ Igbo', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('68', 'ik', 'Inupiaq', 'Iñupiaq, Iñupiatun', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('69', 'io', 'Ido', 'Ido', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('70', 'is', 'Icelandic', 'Íslenska', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('71', 'it', 'Italian', 'Italiano', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('72', 'iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('73', 'ja', 'Japanese', '日本語 (にほんご／にっぽんご)', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('74', 'jv', 'Javanese', 'basa Jawa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('75', 'kl', 'Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('76', 'kn', 'Kannada', 'ಕನ್ನಡ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('77', 'kr', 'Kanuri', 'Kanuri', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('78', 'ks', 'Kashmiri', 'कश्मीरी, كشميري‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('79', 'kk', 'Kazakh', 'Қазақ тілі', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('80', 'km', 'Khmer', 'ភាសាខ្មែរ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('81', 'ki', 'Kikuyu, Gikuyu', 'Gĩkũyũ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('82', 'rw', 'Kinyarwanda', 'Ikinyarwanda', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('83', 'ky', 'Kirghiz, Kyrgyz', 'кыргыз тили', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('84', 'kv', 'Komi', 'коми кыв', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('85', 'kg', 'Kongo', 'KiKongo', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('86', 'ko', 'Korean', '한국어 (韓國語), 조선말 (朝鮮語)', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('87', 'ku', 'Kurdish', 'Kurdî, كوردی‎', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('88', 'kj', 'Kwanyama, Kuanyama', 'Kuanyama', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('89', 'la', 'Latin', 'latine, lingua latina', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('90', 'lb', 'Luxembourgish, Letzeburgesch', 'Lëtzebuergesch', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('91', 'lg', 'Luganda', 'Luganda', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('92', 'li', 'Limburgish, Limburgan, Limburger', 'Limburgs', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('93', 'ln', 'Lingala', 'Lingála', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('94', 'lo', 'Lao', 'ພາສາລາວ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('95', 'lt', 'Lithuanian', 'lietuvių kalba', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('96', 'lu', 'Luba-Katanga', 'Kiluba', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('97', 'lv', 'Latvian', 'latviešu valoda', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('98', 'gv', 'Manx', 'Gaelg, Gailck', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('99', 'mk', 'Macedonian', 'македонски јазик', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('100', 'mg', 'Malagasy', 'Malagasy fiteny', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('101', 'ms', 'Malay', 'bahasa Melayu, بهاس ملايو‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('102', 'ml', 'Malayalam', 'മലയാളം', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('103', 'mt', 'Maltese', 'Malti', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('104', 'mi', 'Māori', 'te reo Māori', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('105', 'mr', 'Marathi (Marāṭhī)', 'मराठी', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('106', 'mh', 'Marshallese', 'Kajin M̧ajeļ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('107', 'mn', 'Mongolian', 'монгол', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('108', 'na', 'Nauru', 'Ekakairũ Naoero', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('109', 'nv', 'Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('110', 'nb', 'Norwegian Bokmål', 'Norsk bokmål', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('111', 'nd', 'North Ndebele', 'isiNdebele', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('112', 'ne', 'Nepali', 'नेपाली', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('113', 'ng', 'Ndonga', 'Owambo', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('114', 'nn', 'Norwegian Nynorsk', 'Norsk nynorsk', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('115', 'no', 'Norwegian', 'Norsk', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('116', 'ii', 'Nuosu', 'ꆈꌠ꒿ Nuosuhxop', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('117', 'nr', 'South Ndebele', 'isiNdebele', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('118', 'oc', 'Occitan', 'Occitan', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('119', 'oj', 'Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('120', 'cu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'ѩзыкъ словѣньскъ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('121', 'om', 'Oromo', 'Afaan Oromoo', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('122', 'or', 'Oriya', 'ଓଡ଼ିଆ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('123', 'os', 'Ossetian, Ossetic', 'ирон æвзаг', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('124', 'pa', 'Panjabi, Punjabi', 'ਪੰਜਾਬੀ, پنجابی‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('125', 'pi', 'Pāli', 'पाऴि', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('126', 'fa', 'Persian', 'فارسی', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('127', 'pl', 'Polish', 'polski', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('128', 'ps', 'Pashto, Pushto', 'پښتو', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('129', 'pt', 'Portuguese', 'Português', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('130', 'qu', 'Quechua', 'Runa Simi, Kichwa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('131', 'rm', 'Romansh', 'rumantsch grischun', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('132', 'rn', 'Kirundi', 'kiRundi', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('133', 'ro', 'Romanian', 'română', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('134', 'ru', 'Russian', 'русский язык', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('135', 'sa', 'Sanskrit (Saṁskṛta)', 'संस्कृतम्', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('136', 'sc', 'Sardinian', 'sardu', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('137', 'sd', 'Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('138', 'se', 'Northern Sami', 'Davvisámegiella', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('139', 'sm', 'Samoan', 'gagana faa Samoa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('140', 'sg', 'Sango', 'yângâ tî sängö', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('141', 'sr', 'Serbian', 'српски језик', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('142', 'gd', 'Scottish Gaelic; Gaelic', 'Gàidhlig', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('143', 'sn', 'Shona', 'chiShona', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('144', 'si', 'Sinhala, Sinhalese', 'සිංහල', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('145', 'sk', 'Slovak', 'slovenčina', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('146', 'sl', 'Slovene', 'slovenščina', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('147', 'so', 'Somali', 'Soomaaliga, af Soomaali', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('148', 'st', 'Southern Sotho', 'Sesotho', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('149', 'es', 'Spanish; Castilian', 'español, castellano', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('150', 'su', 'Sundanese', 'Basa Sunda', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('151', 'sw', 'Swahili', 'Kiswahili', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('152', 'ss', 'Swati', 'SiSwati', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('153', 'sv', 'Swedish', 'svenska', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('154', 'ta', 'Tamil', 'தமிழ்', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('155', 'te', 'Telugu', 'తెలుగు', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('156', 'tg', 'Tajik', 'тоҷикӣ, toğikī, تاجیکی‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('157', 'th', 'Thai', 'ไทย', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('158', 'ti', 'Tigrinya', 'ትግርኛ', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('159', 'bo', 'Tibetan Standard, Tibetan, Central', 'བོད་ཡིག', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('160', 'tk', 'Turkmen', 'Türkmen, Түркмен', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('161', 'tl', 'Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('162', 'tn', 'Tswana', 'Setswana', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('163', 'to', 'Tonga (Tonga Islands)', 'faka Tonga', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('164', 'tr', 'Turkish', 'Türkçe', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('165', 'ts', 'Tsonga', 'Xitsonga', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('166', 'tt', 'Tatar', 'татарча, tatarça, تاتارچا‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('167', 'tw', 'Twi', 'Twi', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('168', 'ty', 'Tahitian', 'Reo Tahiti', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('169', 'ug', 'Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('170', 'uk', 'Ukrainian', 'українська', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('171', 'ur', 'Urdu', 'اردو', 'rtl');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('172', 'uz', 'Uzbek', 'zbek, Ўзбек, أۇزبېك‎', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('173', 've', 'Venda', 'Tshivenḓa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('174', 'vi', 'Vietnamese', 'Tiếng Việt', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('175', 'vo', 'Volapük', 'Volapük', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('176', 'wa', 'Walloon', 'Walon', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('177', 'cy', 'Welsh', 'Cymraeg', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('178', 'wo', 'Wolof', 'Wollof', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('179', 'fy', 'Western Frisian', 'Frysk', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('180', 'xh', 'Xhosa', 'isiXhosa', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('181', 'yi', 'Yiddish', 'ייִדיש', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('182', 'yo', 'Yoruba', 'Yorùbá', 'ltr');
INSERT INTO `languages` (`id`, `code`, `name`, `name_native`, `dir`) VALUES ('183', 'za', 'Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh', 'ltr');
